#!/usr/bin/env expect

spawn nix repl
expect "nix-repl>"
send "hm = import <home-manager/modules> { configuration = ~/.config/home-manager/home.nix; pkgs = import <nixpkgs> {}; }\n"
expect "nix-repl>"
send ":p hm.config.kirby\n"
expect ":p hm.config.kirby\n"
expect "(.*)nix-repl>"

